
String passeUrl = "www.zain-stores.com";  //done
String serviceName="/ad_panel/zainapi/categoriesparent";  //done
String categories="/ad_panel/zainapi/categories";  //done
String productHome="/ad_panel/zainapi/categoriessup";  //done
String pro="/ad_panel/zainapi/products";  //done
String register = "/ad_panel/zainapi/customerRegister";  //done
String login = "/ad_panel/zainapi/customerLogin";  //done
String Profile = "/ad_panel/zainapi/customerProfile";  //done
String updateProfile = "/ad_panel/zainapi/customerUpdateProfile"; //done
String settings = "/ad_panel/zainapi/customercount";//done
String favoriteAdd = "/ad_panel/zainapi/customerAddFavourite";  //done
// String getSize = "/ad_panel/zainapi/getsize";
String addCart = "/ad_panel/zainapi/customerAddCart"; //done
String showCartUrl ="/ad_panel/zainapi/customerCart"; //done
String categoriesAll = "/ad_panel/zainapi/categoriesall"; //done
String page ="/ad_panel/zainapi/pages";  //done aboutpage
String removeCartApi ="/ad_panel/zainapi/customerRemoveCart";  //done
String addAddressApi ="/ad_panel/zainapi/customerNewAddress";//done
String showAddressApi ="/ad_panel/zainapi/customerAddresses";//done
String updateAddress ="/ad_panel/zainapi/customerUpdateAddress";
String removeAddress ="/ad_panel/zainapi/customerDelAddress";
String country ="/ad_panel/zainapi/countries";  //done
String region ="/ad_panel/zainapi/regions"; //TODO city and done
String promo ="/ad_panel/zainapi/promocode";  //done
String customerNewOrderCart ="/ad_panel/zainapi/customerNewOrderFromCart"; //TODO ordersure new order
String customerOrder ="/ad_panel/zainapi/customerOrders"; //TODO orderShow
String chatShowUrl ="/ad_panel/zainapi/supportMessages";
